"""init_database

Revision ID: 851b700a64af
Revises: 
Create Date: 2026-07-08 09:15:28.203018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '851b700a64af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_job',
    sa.Column('job_type', sa.String(length=64), nullable=False, comment='e.g., knowledge_extraction, summarization, embedding'),
    sa.Column('provider', sa.String(length=64), nullable=False, comment='e.g., deepseek, openai, bge'),
    sa.Column('model', sa.String(length=128), nullable=False, comment='Model name used'),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True, comment='Input token count'),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True, comment='Output token count'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='pending, running, completed, failed'),
    sa.Column('error', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_source',
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='e.g., chatgpt_export, manual_input'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Human-readable name of the source'),
    sa.Column('file_path', sa.Text(), nullable=True, comment='Original file path or identifier'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Arbitrary source metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=64), nullable=False, comment='Tag name'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conversation',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True, comment='Conversation title'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI-generated summary of the conversation'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Conversation metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge',
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False, comment='Knowledge title'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full knowledge content'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Short summary / abstract'),
    sa.Column('category', sa.String(length=128), nullable=True, comment='Category label'),
    sa.Column('importance', sa.Float(), nullable=True, comment='Importance score (0.0 - 1.0)'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional metadata'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_conversation_id'), 'knowledge', ['conversation_id'], unique=False)
    op.create_table('message',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False, comment='e.g., user, assistant, system'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Order within the conversation'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_table('knowledge_chunk',
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Sequential index within the knowledge item'),
    sa.Column('content', sa.Text(), nullable=False, comment='Chunk text content'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Approximate token count'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunk_knowledge_id'), 'knowledge_chunk', ['knowledge_id'], unique=False)
    op.create_table('knowledge_tag',
    sa.Column('knowledge_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_id', 'tag_id')
    )
    op.create_table('embedding',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False, comment='Embedding model name'),
    sa.Column('dimension', sa.Integer(), nullable=False, comment='Vector dimension'),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False, comment='pgvector embedding (up to 1024 dimensions)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_chunk_id'), 'embedding', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embedding_chunk_id'), table_name='embedding')
    op.drop_table('embedding')
    op.drop_table('knowledge_tag')
    op.drop_index(op.f('ix_knowledge_chunk_knowledge_id'), table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_knowledge_conversation_id'), table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_table('conversation')
    op.drop_table('tag')
    op.drop_table('knowledge_source')
    op.drop_table('ai_job')
    # ### end Alembic commands ###
