"""Fix the initial migration file to add CREATE EXTENSION vector."""

MIGRATION_FILE = "migrations/versions/851b700a64af_init_database.py"

with open(MIGRATION_FILE) as f:
    content = f.read()

# Add import for pgvector (if not already in import section)
old_import = "from alembic import op\nimport sqlalchemy as sa"
new_import = "from alembic import op\nimport sqlalchemy as sa\nimport pgvector.sqlalchemy"
# Check if pgvector import is already in the imports (before the revision section)
if "import pgvector" not in content.split("revision:")[0]:
    content = content.replace(old_import, new_import)
    print("Added pgvector import")
else:
    print("pgvector import already present")

# Add CREATE EXTENSION vector at beginning of upgrade
old_upgrade = (
    'def upgrade() -> None:\n'
    '    """Upgrade schema."""\n'
    '    # ### commands auto generated by Alembic - please adjust! ###'
)
new_upgrade = (
    'def upgrade() -> None:\n'
    '    """Upgrade schema."""\n'
    '    # Enable pgvector extension\n'
    '    op.execute("CREATE EXTENSION IF NOT EXISTS vector")\n'
    '    # ### commands auto generated by Alembic - please adjust! ###'
)
if old_upgrade in content:
    content = content.replace(old_upgrade, new_upgrade)
    print("Added CREATE EXTENSION vector")
else:
    print("Upgrade section pattern not found")

# Fix knowledge_tag table - remove extra id, created_at, updated_at columns
old_kt = (
    "    op.create_table('knowledge_tag',\n"
    "    sa.Column('knowledge_id', sa.UUID(), nullable=False),\n"
    "    sa.Column('tag_id', sa.UUID(), nullable=False),\n"
    "    sa.Column('id', sa.UUID(), nullable=False),\n"
    "    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),\n"
    "    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),\n"
    "    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ondelete='CASCADE'),\n"
    "    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),\n"
    "    sa.PrimaryKeyConstraint('knowledge_id', 'tag_id', 'id')\n"
    "    )"
)
new_kt = (
    "    op.create_table('knowledge_tag',\n"
    "    sa.Column('knowledge_id', sa.UUID(), nullable=False),\n"
    "    sa.Column('tag_id', sa.UUID(), nullable=False),\n"
    "    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ondelete='CASCADE'),\n"
    "    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),\n"
    "    sa.PrimaryKeyConstraint('knowledge_id', 'tag_id')\n"
    "    )"
)
if old_kt in content:
    content = content.replace(old_kt, new_kt)
    print("Fixed knowledge_tag table (removed extra id/timestamp columns)")
else:
    print("knowledge_tag table already clean")

with open(MIGRATION_FILE, "w") as f:
    f.write(content)

print("Migration file fix complete")
